var groups_spaces_4326 = {
    "type": "FeatureCollection",
    "name": "groups_spaces_4326",
    "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
    "features": [
        { "type": "Feature", "properties": { "fid": 1, "Typ": "space", "Webseite": "https://megahertz-hannover.org", "Stadt": "Hannover", "Mailingliste": null, "E-Mail": "kontakt@megahertz-hannover.org", "Mastodon": null, "Name": "Megahertz", "count_fictive": 18, "Rocket": "#hannover, #megahertz" }, "geometry": { "type": "Point", "coordinates": [ 9.717929208062385, 52.388138641145147 ] } },
        { "type": "Feature", "properties": { "fid": 3, "Typ": "space", "Webseite": "https://geekfem.net/", "Stadt": "Hamburg", "Mailingliste": null, "E-Mail": "geekfem@hamburg.ccc.de", "Mastodon": "https://chaos.social/@geekfem", "Name": "Geekfem", "count_fictive": 25, "Treffen": "Jeden dritten Donnerstag im Monat beim CCCHH" }, "geometry": { "type": "Point", "coordinates": [ 9.944652800134557, 53.558470729382726 ] } },
        { "type": "Feature", "properties": { "fid": 4, "Typ": "space", "Webseite": "https://entropia.de/Haecksen@entropia", "Stadt": "Karlsruhe", "Mailingliste": "https://lists.entropia.de/postorius/lists/haecksen.lists.entropia.de/", "E-Mail": null, "Mastodon": null, "Name": "Entropia e.V.", "count_fictive": 14 }, "geometry": { "type": "Point", "coordinates": [ 8.407171511064279, 49.006501030903777 ] } },
        { "type": "Feature", "properties": { "fid": 5, "Typ": "group", "Webseite": null, "Stadt": "Stuttgart", "Mailingliste": "stuttgart@lists.haecksen.org", "E-Mail": null, "Mastodon": null, "Name": null, "count_fictive": 10, "Kontaktperson": "Princess princess@bofh.de", "Treffen": "Unregelmäßige Treffen, werden über die Mailingliste verabredet" }, "geometry": { "type": "Point", "coordinates": [ 9.181507622704977, 48.783677891262812 ] } },
        { "type": "Feature", "properties": { "fid": 6, "Typ": "group", "Webseite": null, "Stadt": "Frankfurt, Mainz, Wiesbaden", "Mailingliste": null, "E-Mail": null, "Mastodon": null, "Name": null, "count_fictive": 24 }, "geometry": { "type": "Point", "coordinates": [ 8.66373830078803, 50.106811036269249 ] } },
        { "type": "Feature", "properties": { "fid": 7, "Typ": "group", "Webseite": null, "Stadt": "Berlin", "Mailingliste": "mail to: c47@rct.in-berlin.de", "E-Mail": null, "Mastodon": "https://chaos.social/@Haecksen_Berlin", "Name": null, "count_fictive": 11, "Treffen": "Zweites Wochenende im Monat, Sa/So wechselnd, 15:00 Uhr, Ort wechselt", "Rocket": "#berlin" }, "geometry": { "type": "Point", "coordinates": [ 13.370939989578533, 52.525110808876995 ] } },
        { "type": "Feature", "properties": { "fid": 8, "Typ": "space", "Webseite": "https://acmelabs.space/meetups/flinta/", "Stadt": "Bielefeld", "Mailingliste": "http://announce@acmelabs.space/", "E-Mail": null, "Mastodon": null, "Name": "ACME Labs e.V.", "count_fictive": 42, "Treffen": null, "Rocket": null }, "geometry": { "type": "Point", "coordinates": [ 8.546548841579767, 52.02044265241647 ] } },
        { "type": "Feature", "properties": { "fid": 9, "Typ": "space", "Webseite": "https://wiki.ccchb.de/wiki/Haecksen", "Stadt": "Bremen", "Mailingliste": null, "E-Mail": "haecksen@ccchb.de", "Mastodon": null, "Name": "CCC Bremen e.V.", "count_fictive": 13, "Kontaktperson": "MoniKa", "Rocket": "#bremen" }, "geometry": { "type": "Point", "coordinates": [ 8.787881321802859, 53.086470020056865 ] } },
        { "type": "Feature", "properties": { "fid": 10, "Typ": "group", "Webseite": null, "Stadt": "Leipzig", "Mailingliste": null, "E-Mail": "haecksen_leipzig@systemli.org", "Mastodon": null, "Name": null, "count_fictive": 8, "Treffen": "Jeden letzten Dienstag im Monat ab 19 Uhr", "Rocket": "#leipzig" }, "geometry": { "type": "Point", "coordinates": [ 12.381902937086744, 51.345724328848966 ] } },
        { "type": "Feature", "properties": { "fid": 11, "Typ": "space", "Webseite": "https://wiki.cccgoe.de/wiki/Haecksen", "Stadt": "Göttingen", "Mailingliste": null, "E-Mail": "haecksen@cccgoe.de", "Mastodon": null, "Name": "Neotopia", "count_fictive": 7, "Treffen": "Zweimal monatlich" }, "geometry": { "type": "Point", "coordinates": [ 9.945084767129609, 51.545423444935238 ] } },
        { "type": "Feature", "properties": { "fid": 12, "Typ": "group", "Webseite": null, "Stadt": "Freiburg, Basel", "Mailingliste": null, "E-Mail": null, "Mastodon": null, "Name": null, "count_fictive": 9, "Treffen": "Jeden 2. Do im Monat beim cccFr", "Rocket": "#freiburgUndBasel, #haecksen_basel" }, "geometry": { "type": "Point", "coordinates": [ 7.84131252726814, 47.997913641952749 ] } },
        { "type": "Feature", "properties": { "fid": 13, "Typ": "group", "Webseite": "https://haecksen.nuernberg.page", "Stadt": "Nürnberg/Erlangen/Fürth", "Mailingliste": null, "E-Mail": "haecksen@nuernberg.page", "Mastodon": null, "Name": null, "count_fictive": 11, "Treffen": "Jeden ersten Dienstag im Monat ab 18.30 Uhr, Ort wechselt", "Rocket": "#Nuernberg-Erlangen-Fuerth" }, "geometry": { "type": "Point", "coordinates": [ 11.082585649957592, 49.445237631795656 ] } },
        { "type": "Feature", "properties": { "fid": 14, "Typ": "group", "Webseite": null, "Stadt": "Darmstadt", "Mailingliste": null, "E-Mail": null, "Mastodon": null, "Name": null, "count_fictive": 17 }, "geometry": { "type": "Point", "coordinates": [ 8.629501514485213, 49.872925433265515 ] } },
        { "type": "Feature", "properties": { "fid": 15, "Typ": "group", "Webseite": null, "Stadt": "Osnabrück", "Mailingliste": null, "E-Mail": null, "Mastodon": null, "Name": null, "count_fictive": 5 }, "geometry": { "type": "Point", "coordinates": [ 8.061554895903779, 52.272946043841372 ] } },
        { "type": "Feature", "properties": { "fid": 16, "Typ": "group", "Webseite": null, "Stadt": "Braunschweig", "Mailingliste": null, "E-Mail": null, "Mastodon": null, "Name": null, "count_fictive": 6, "Kontaktperson": "naerrin", "Treffen": "unregelmäßig, lange Pausen", "Rocket": "#braunschweig" }, "geometry": { "type": "Point", "coordinates": [ 10.540226543631663, 52.252223949096219 ] } },
        { "type": "Feature", "properties": { "fid": 17, "Typ": "group", "Webseite": null, "Stadt": "Bamberg", "Mailingliste": null, "E-Mail": null, "Mastodon": null, "Name": null, "count_fictive": 3 }, "geometry": { "type": "Point", "coordinates": [ 10.899700693090942, 49.900667658074106 ] } },
        { "type": "Feature", "properties": { "fid": 18, "Typ": "group", "Webseite": null, "Stadt": "Aachen", "Mailingliste": null, "E-Mail": null, "Mastodon": null, "Name": null, "count_fictive": 1, "Kontaktperson": "mosh", "Treffen": null }, "geometry": { "type": "Point", "coordinates": [ 6.091233570945875, 50.767765025584687 ] } },
        { "type": "Feature", "properties": { "fid": 19, "Typ": "group", "Webseite": null, "Stadt": "Helsinki", "Mailingliste": null, "E-Mail": null, "Mastodon": null, "Name": null, "count_fictive": 1, "Kontaktperson": "saliente", "Treffen": null, "Rocket": null }, "geometry": { "type": "Point", "coordinates": [ 24.941350327237767, 60.171856782158379 ] } },
        { "type": "Feature", "properties": { "fid": 20, "Typ": "group", "Webseite": null, "Stadt": "Nordrhein-Westfalen", "Mailingliste": null, "E-Mail": null, "Mastodon": null, "Name": null, "count_fictive": 8, "Kontaktperson": null, "Treffen": null, "Rocket": "#Da-NRW-lokales-Treffen" }, "geometry": { "type": "Point", "coordinates": [ 6.793525422960415, 51.219628687358281 ] } },
        { "type": "Feature", "properties": { "fid": 21, "Typ": "group", "Webseite": null, "Stadt": "München", "Mailingliste": null, "E-Mail": null, "Mastodon": null, "Name": null, "count_fictive": null, "Kontaktperson": "Smettbo", "Treffen": "Treffen am vierten Sonntag im Monat", "Rocket": "#muenchen, #muc_Haecksen" }, "geometry": { "type": "Point", "coordinates": [ 11.556652907142707, 48.140750972786236 ] } },
        { "type": "Feature", "properties": { "fid": 22, "Typ": "group", "Webseite": null, "Stadt": "Wien", "Mailingliste": null, "E-Mail": null, "Mastodon": null, "Name": null, "count_fictive": 2, "Kontaktperson": null, "Treffen": null, "Rocket": "#wien" }, "geometry": { "type": "Point", "coordinates": [ 16.377896885624935, 48.185010078294425 ] } }
    ]
}
