var groups_spaces_4326 = {
"type": "FeatureCollection",
"name": "groups_spaces_4326",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
    { "type": "Feature", "properties": { "fid": 1, "typ": "space", "website": "https://megahertz-hannover.org", "city_town": "Hannover", "mailingliste": null, "email": "kontakt@megahertz-hannover.org", "mastodon": null, "space_name": "Megahertz", "count_fictive": 18, "rocket": "#hannover, #megahertz" }, "geometry": { "type": "Point", "coordinates": [ 9.717929208062385, 52.388138641145147 ] } },
    { "type": "Feature", "properties": { "fid": 3, "typ": "space", "website": "https://geekfem.net/", "city_town": "Hamburg", "mailingliste": null, "email": "geekfem@hamburg.ccc.de", "mastodon": "https://chaos.social/@geekfem", "space_name": "Geekfem", "count_fictive": 25, "meetings": "Jeden dritten Donnerstag im Monat beim CCCHH" }, "geometry": { "type": "Point", "coordinates": [ 9.944652800134557, 53.558470729382726 ] } },
    { "type": "Feature", "properties": { "fid": 4, "typ": "space", "website": "https://entropia.de/Haecksen@entropia", "city_town": "Karlsruhe", "mailingliste": "https://lists.entropia.de/postorius/lists/haecksen.lists.entropia.de/", "email": null, "mastodon": null, "space_name": "Entropia e.V.", "count_fictive": 14 }, "geometry": { "type": "Point", "coordinates": [ 8.407171511064279, 49.006501030903777 ] } },
    { "type": "Feature", "properties": { "fid": 5, "typ": "group", "website": null, "city_town": "Stuttgart", "mailingliste": "stuttgart@lists.haecksen.org", "email": null, "mastodon": null, "space_name": null, "count_fictive": 10, "contact_person": "Princess princess@bofh.de", "meetings": "Unregelmäßige Treffen, werden über die Mailingliste verabredet" }, "geometry": { "type": "Point", "coordinates": [ 9.181507622704977, 48.783677891262812 ] } },
    { "type": "Feature", "properties": { "fid": 6, "typ": "group", "website": null, "city_town": "Frankfurt, Mainz, Wiesbaden", "mailingliste": null, "email": null, "mastodon": null, "space_name": null, "count_fictive": 24 }, "geometry": { "type": "Point", "coordinates": [ 8.66373830078803, 50.106811036269249 ] } },
    { "type": "Feature", "properties": { "fid": 7, "typ": "group", "website": null, "city_town": "Berlin", "mailingliste": "mail to: c47@rct.in-berlin.de", "email": null, "mastodon": "https://chaos.social/@Haecksen_Berlin", "space_name": null, "count_fictive": 11, "meetings": "Zweites Wochenende im Monat, Sa/So wechselnd, 15:00 Uhr, Ort wechselt", "rocket": "#berlin" }, "geometry": { "type": "Point", "coordinates": [ 13.370939989578533, 52.525110808876995 ] } },
    { "type": "Feature", "properties": { "fid": 8, "typ": "space", "website": "https://acmelabs.space/meetups/flinta/", "city_town": "Bielefeld", "mailingliste": "http://announce@acmelabs.space/", "email": null, "mastodon": null, "space_name": "ACME Labs e.V.", "count_fictive": 42, "meetings": null, "rocket": null }, "geometry": { "type": "Point", "coordinates": [ 8.546548841579767, 52.02044265241647 ] } },
    { "type": "Feature", "properties": { "fid": 9, "typ": "space", "website": "https://wiki.ccchb.de/wiki/Haecksen", "city_town": "Bremen", "mailingliste": null, "email": "haecksen@ccchb.de", "mastodon": null, "space_name": "CCC Bremen e.V.", "count_fictive": 13, "contact_person": "MoniKa", "rocket": "#bremen" }, "geometry": { "type": "Point", "coordinates": [ 8.787881321802859, 53.086470020056865 ] } },
    { "type": "Feature", "properties": { "fid": 10, "typ": "group", "website": null, "city_town": "Leipzig", "mailingliste": null, "email": "haecksen_leipzig@systemli.org", "mastodon": null, "space_name": null, "count_fictive": 8, "meetings": "Jeden letzten Dienstag im Monat ab 19 Uhr", "rocket": "#leipzig" }, "geometry": { "type": "Point", "coordinates": [ 12.381902937086744, 51.345724328848966 ] } },
    { "type": "Feature", "properties": { "fid": 11, "typ": "space", "website": "https://wiki.cccgoe.de/wiki/Haecksen", "city_town": "Göttingen", "mailingliste": null, "email": "haecksen@cccgoe.de", "mastodon": null, "space_name": "Neotopia", "count_fictive": 7, "meetings": "Zweimal monatlich" }, "geometry": { "type": "Point", "coordinates": [ 9.945084767129609, 51.545423444935238 ] } },
    { "type": "Feature", "properties": { "fid": 12, "typ": "group", "website": null, "city_town": "Freiburg, Basel", "mailingliste": null, "email": null, "mastodon": null, "space_name": null, "count_fictive": 9, "meetings": "Jeden 2. Do im Monat beim cccFr", "rocket": "#freiburgUndBasel, #haecksen_basel" }, "geometry": { "type": "Point", "coordinates": [ 7.84131252726814, 47.997913641952749 ] } },
    { "type": "Feature", "properties": { "fid": 13, "typ": "group", "website": "https://haecksen.nuernberg.page", "city_town": "Nürnberg/Erlangen/Fürth", "mailingliste": null, "email": "haecksen@nuernberg.page", "mastodon": null, "space_name": null, "count_fictive": 11, "meetings": "Jeden ersten Dienstag im Monat ab 18.30 Uhr, Ort wechselt", "rocket": "#Nuernberg-Erlangen-Fuerth" }, "geometry": { "type": "Point", "coordinates": [ 11.082585649957592, 49.445237631795656 ] } },
    { "type": "Feature", "properties": { "fid": 14, "typ": "group", "website": null, "city_town": "Darmstadt", "mailingliste": null, "email": null, "mastodon": null, "space_name": null, "count_fictive": 17 }, "geometry": { "type": "Point", "coordinates": [ 8.629501514485213, 49.872925433265515 ] } },
    { "type": "Feature", "properties": { "fid": 15, "typ": "group", "website": null, "city_town": "Osnabrück", "mailingliste": null, "email": null, "mastodon": null, "space_name": null, "count_fictive": 5 }, "geometry": { "type": "Point", "coordinates": [ 8.061554895903779, 52.272946043841372 ] } },
    { "type": "Feature", "properties": { "fid": 16, "typ": "group", "website": null, "city_town": "Braunschweig", "mailingliste": null, "email": null, "mastodon": null, "space_name": null, "count_fictive": 6, "contact_person": "naerrin", "meetings": "unregelmäßig, lange Pausen", "rocket": "#braunschweig" }, "geometry": { "type": "Point", "coordinates": [ 10.540226543631663, 52.252223949096219 ] } },
    { "type": "Feature", "properties": { "fid": 17, "typ": "group", "website": null, "city_town": "Bamberg", "mailingliste": null, "email": null, "mastodon": null, "space_name": null, "count_fictive": 3 }, "geometry": { "type": "Point", "coordinates": [ 10.899700693090942, 49.900667658074106 ] } },
    { "type": "Feature", "properties": { "fid": 18, "typ": "group", "website": null, "city_town": "Aachen", "mailingliste": null, "email": null, "mastodon": null, "space_name": null, "count_fictive": 1, "contact_person": "mosh", "meetings": null }, "geometry": { "type": "Point", "coordinates": [ 6.091233570945875, 50.767765025584687 ] } },
    { "type": "Feature", "properties": { "fid": 19, "typ": "group", "website": null, "city_town": "Helsinki", "mailingliste": null, "email": null, "mastodon": null, "space_name": null, "count_fictive": 1, "contact_person": "saliente", "meetings": null, "rocket": null }, "geometry": { "type": "Point", "coordinates": [ 24.941350327237767, 60.171856782158379 ] } },
    { "type": "Feature", "properties": { "fid": 20, "typ": "group", "website": null, "city_town": "Nordrhein-Westfalen", "mailingliste": null, "email": null, "mastodon": null, "space_name": null, "count_fictive": 8, "contact_person": null, "meetings": null, "rocket": "#Da-NRW-lokales-Treffen" }, "geometry": { "type": "Point", "coordinates": [ 6.793525422960415, 51.219628687358281 ] } },
    { "type": "Feature", "properties": { "fid": 21, "typ": "group", "website": null, "city_town": "München", "mailingliste": null, "email": null, "mastodon": null, "space_name": null, "count_fictive": null, "contact_person": "Smettbo", "meetings": "Treffen am vierten Sonntag im Monat", "rocket": "#muenchen, #muc_Haecksen" }, "geometry": { "type": "Point", "coordinates": [ 11.556652907142707, 48.140750972786236 ] } },
    { "type": "Feature", "properties": { "fid": 22, "typ": "group", "website": null, "city_town": "Wien", "mailingliste": null, "email": null, "mastodon": null, "space_name": null, "count_fictive": 2, "contact_person": null, "meetings": null, "rocket": "#wien" }, "geometry": { "type": "Point", "coordinates": [ 16.377896885624935, 48.185010078294425 ] } }
    ]
}
